### PR TITLE
ECO-1336: Revamping storybook to make it easier to implement UI changes in the sdk

### PR DESCRIPTION
**Pull request by nicfix**
## Motivation / Description
We need to implement some appearance changes due to customisation.
This PR sets up again storybook (updated) to create directly stories in svelte and test them directly instead of doing back and forth with the demo app.

## Changes introduced
* Updated storybook
* Fixed the main.ts setup
* Started working on a story for the components affected by customisation

### CODE REVIEW

**Review by guido732 — COMMENTED** [review]
looks good, although when I install dependencies and try to run the storybook command I get this when trying to view a story 
image

**Comment by guido732** [comment]
also, we should add `storybook-static` to the `.gitignore` file

**Comment by nicfix** [comment]
The one you picked is the old story we had and it doesn't work anymore, I think we should not use storybook that way, I'll remove it (we still have it in git if we want in the future).

**Comment by nicfix** [comment]
Done both!

**Review by guido732 — APPROVED** [review]

**Pull request merged**
